
(function(){
var io='IntersectionObserver' in window?new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add('in');[].forEach.call(e.target.querySelectorAll('.ring'),function(r){var d=r.getAttribute('data-d'),o=r.getAttribute('data-o')||0;r.style.strokeDasharray=d+' 999';r.style.strokeDashoffset=-o;});[].forEach.call(e.target.querySelectorAll('.ly'),function(l,i){l.style.transform='translateY('+(i*10)+'px)';});io.unobserve(e.target);}});},{threshold:.25}):null;
[].forEach.call(document.querySelectorAll('.io'),function(el){if(io)io.observe(el);else el.classList.add('in');});
var ST=[{"n": "Attention", "h": "Win the first 50 milliseconds", "l": ["A headline that states the outcome, not the company name", "One strong visual, real photos over stock", "Fast: the page paints before they give up"]}, {"n": "Clarity", "h": "What, for whom, why you", "l": ["What you do and where, in the first screen", "Who it is for, in their words", "The single reason you beat the alternatives"]}, {"n": "Trust", "h": "Remove the doubt", "l": ["Reviews with names and specifics beside the promise", "Faces, credentials, years in business", "What happens after they call, written down"]}, {"n": "Friction", "h": "Make yes easy", "l": ["Tap-to-call at the top and bottom", "Short forms: name, phone, one question", "Nothing that makes a phone user pinch or wait"]}, {"n": "Offer", "h": "A reason to act now", "l": ["A concrete next step: audit, estimate, consult", "Honest urgency only, never fake countdowns", "Risk reversal: no contract to start, clear pricing"]}, {"n": "Action", "h": "One obvious button", "l": ["One primary call to action per screen", "Buttons that say what happens: Get my free audit", "The number is a button, not just text"]}, {"n": "Follow-up", "h": "Speed to lead", "l": ["Reply within the hour when you can, same day always", "A real person, not a drip sequence", "Track which ads and pages produce the calls"]}],det=document.getElementById('ttDetail');
function show(i){var s=ST[i];det.innerHTML='<h3>'+(i+1)+'. '+s.n+': '+s.h+'</h3><ul>'+s.l.map(function(x){return '<li>'+x+'</li>';}).join('')+'</ul>';
 [].forEach.call(document.querySelectorAll('.tt-steps button'),function(b){b.setAttribute('aria-pressed',+b.dataset.i===i?'true':'false');});[].forEach.call(document.querySelectorAll('.tt-stack .ly'),function(l){l.classList.toggle('on',+l.dataset.i===i);});}
[].forEach.call(document.querySelectorAll('.tt-steps button,.tt-stack .ly'),function(b){b.addEventListener('click',function(){show(+b.dataset.i);});});show(0);
var AX=['Brand','Message','Trust','Conversion'],ADV={Brand:'Your weakest layer is brand. Start with the one-sentence promise and a look people would recognize with the name covered.',Message:'Your weakest layer is message. Make the first screen say what, where and for whom, and give your ads an angle competitors are not using.',Trust:'Your weakest layer is trust. Move real reviews and photos next to your prices and buttons, and show who they will be talking to.',Conversion:'Your weakest layer is conversion. Make calling a one-tap job on every page and start tracking which ads and pages produce calls.'};
function radar(v){var cx=140,cy=122,R=90,pts=[],grid='';for(var g=1;g<=4;g++){var p=[];for(var i=0;i<4;i++){var a=-Math.PI/2+i*Math.PI/2;p.push((cx+Math.cos(a)*R*g/4).toFixed(1)+','+(cy+Math.sin(a)*R*g/4).toFixed(1));}grid+='<polygon points="'+p.join(' ')+'" fill="none" stroke="rgba(255,255,255,.18)"/>';}
 for(var i=0;i<4;i++){var a=-Math.PI/2+i*Math.PI/2,r=R*v[i];pts.push((cx+Math.cos(a)*r).toFixed(1)+','+(cy+Math.sin(a)*r).toFixed(1));grid+='<text x="'+(cx+Math.cos(a)*(R+18))+'" y="'+(cy+Math.sin(a)*(R+18)+4)+'" text-anchor="middle" font-family="Inter,sans-serif" font-size="12" font-weight="800" fill="#E6EDF7">'+AX[i]+'</text>';}
 document.getElementById('ttRadar').innerHTML='<defs><linearGradient id="ttrg" x1="0" x2="1"><stop offset="0" stop-color="#FACC15"/><stop offset=".5" stop-color="#FB923C"/><stop offset="1" stop-color="#F43F5E"/></linearGradient></defs>'+grid+'<polygon points="'+pts.join(' ')+'" fill="url(#ttrg)" fill-opacity=".55" stroke="#FDBA74" stroke-width="2"/>';}
function score(){var t={},c={};AX.forEach(function(a){t[a]=0;c[a]=0;});var ans=0;[].forEach.call(document.querySelectorAll('#ttQ .row'),function(r){var on=r.querySelector('button[aria-pressed="true"]');c[r.dataset.ax]+=2;if(on){t[r.dataset.ax]+=+on.dataset.v;ans++;}});
 var v=AX.map(function(a){return t[a]/c[a];});radar(v.map(function(x){return Math.max(.06,x);}));if(!ans)return;var tot=Math.round(v.reduce(function(s,x){return s+x;},0)/4*100);document.getElementById('ttScore').textContent=tot+'/100';
 var lo=0,mn=Math.min.apply(null,v),mx=Math.max.apply(null,v);v.forEach(function(x,i){if(x<v[lo])lo=i;});var msg=(ans===8&&mn>=1)?'No weak layer. Your fundamentals are strong, so the gap between you and the next business is execution: sharper creative, faster tests, better offers. That is exactly what the Ad Lab is for.':(mn===mx?'All four layers are even. Start with brand, because a clear promise makes every other layer cheaper.':ADV[AX[lo]]);document.getElementById('ttAdv').textContent=msg+(ans<8?' Answer all eight for the full picture.':'');}
[].forEach.call(document.querySelectorAll('#ttQ .opts button'),function(b){b.addEventListener('click',function(){[].forEach.call(b.parentNode.children,function(x){x.setAttribute('aria-pressed',x===b?'true':'false');});score();});});score();
var V=document.getElementById('ttV'),Cc=document.getElementById('ttC');function lift(){document.getElementById('ttVo').textContent=(+V.value).toLocaleString('en-US');document.getElementById('ttCo').textContent=(+Cc.value).toLocaleString('en-US');document.getElementById('ttLift').textContent='$'+Math.round(V.value*.01*Cc.value).toLocaleString('en-US')+' / month';}
V.addEventListener('input',lift);Cc.addEventListener('input',lift);lift();
var ig=document.getElementById('ttIgnite'),lab=document.getElementById('ttLab');if(ig){ig.addEventListener('click',function(){if(lab.classList.contains('lit'))return;lab.classList.add('lit');ig.innerHTML='<span aria-hidden="true">&#128293;</span> Ignited';setTimeout(overflow,1500);setTimeout(function(){lab.classList.remove('lit');ig.innerHTML='<span aria-hidden="true">&#128293;</span> Ignite advertising';},9000);});}
function overflow(){if(window.matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches)return;var cv=document.createElement('canvas');cv.className='tt-ov';document.body.appendChild(cv);var dpr=Math.min(1.5,window.devicePixelRatio||1),W=innerWidth,H=innerHeight,g=cv.getContext('2d');cv.width=W*dpr;cv.height=H*dpr;g.scale(dpr,dpr);
 var CARD=[[239,83,80],[242,128,58],[245,223,77],[39,163,102],[70,88,184],[142,79,181]],B=[],t0=performance.now(),R=Math.random;
 function sp(r,c){var s=Math.ceil(r*2+14),o=document.createElement('canvas');o.width=o.height=s*dpr;var x=o.getContext('2d');x.scale(dpr,dpr);var cx=s/2,cy=s/2-3;x.fillStyle='rgba(11,27,51,.18)';x.beginPath();x.ellipse(cx+2,cy+r+3,r*.9,r*.28,0,0,6.283);x.fill();var gr=x.createRadialGradient(cx-r*.32,cy-r*.4,0,cx,cy,r);gr.addColorStop(0,'#fff');gr.addColorStop(.09,'#fff');gr.addColorStop(.22,'rgb('+c.map(function(v){return Math.round(v*.55+255*.45);}).join(',')+')');gr.addColorStop(.6,'rgb('+c.join(',')+')');gr.addColorStop(1,'rgb('+c.map(function(v){return Math.round(v*.72);}).join(',')+')');x.fillStyle=gr;x.beginPath();x.arc(cx,cy,r,0,6.283);x.fill();x.strokeStyle='rgba(255,255,255,.75)';x.lineWidth=1.2;x.beginPath();x.arc(cx,cy,r-.6,0,6.283);x.stroke();return o;}
 var n=Math.min(260,Math.round(W/4.5));for(var i=0;i<n;i++){var r=7+R()*26,c=CARD[i%6];B.push({x:R()*W,y:H+r+R()*H*.5,r:r,ty:H-r-R()*H*.36,vy:1.6+R()*2.4,ph:R()*6.28,s:sp(r,c),p:0,pt:0});}
 function frame(t){var e=(t-t0)/1000;g.clearRect(0,0,W,H);var alive=0;for(var i=0;i<B.length;i++){var b=B[i];if(b.p===2)continue;alive++;if(b.y>b.ty)b.y-=b.vy*(1+e*.3);else b.y=b.ty+Math.sin(t/500+b.ph)*1.5;var x=b.x+Math.sin(t/900+b.ph)*4;
   if(e>4.2&&b.p===0&&R()<.04){b.p=1;b.pt=t;}var sc=1,al=1;if(b.p===1){var k=(t-b.pt)/280;if(k>=1){b.p=2;continue;}sc=1+k*.5;al=1-k;}
   var s=b.s.width/dpr*sc;g.globalAlpha=al;g.drawImage(b.s,x-s/2,b.y-s/2,s,s);}g.globalAlpha=1;
   if(e>7.5||!alive){cv.remove();return;}requestAnimationFrame(frame);}requestAnimationFrame(frame);}
})();

(function(){var st=document.getElementById('ltStage');if(!st)return;var S=[].slice.call(st.querySelectorAll('.lt-s')),i=0,dots=document.getElementById('ltDots'),nx=document.getElementById('ltNext'),bk=document.getElementById('ltBack');
var NEXT=['Start the tour','Where budgets leak','Do the math','Why we keep evolving','A 24/7 salesperson','Easier quoting','The same stage','Is this you?','The last question','See the free review'];
S.forEach(function(s,k){var d=document.createElement('button');d.type='button';d.setAttribute('aria-label','Go to slide '+(k+1));d.addEventListener('click',function(){go(k);});dots.appendChild(d);});
function go(k){if(k<0||k>=S.length)return;S.forEach(function(s,j){s.classList.toggle('on',j===k);s.classList.toggle('prev',j<k);});i=k;[].forEach.call(dots.children,function(d,j){d.classList.toggle('on',j===k);});
 document.getElementById('ltStep').textContent='Step '+(k+1)+' of '+S.length;document.getElementById('ltNextT').textContent=NEXT[k];bk.style.visibility=k?'visible':'hidden';if(k===6)quote();}
nx.addEventListener('click',function(){if(i<S.length-1)go(i+1);else{var f=document.getElementById('bottom-form');if(f)f.scrollIntoView({behavior:'smooth'});}});bk.addEventListener('click',function(){go(i-1);});
document.addEventListener('keydown',function(e){var r=st.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return;if(e.key==='ArrowRight')go(i+1);if(e.key==='ArrowLeft')go(i-1);});
var x0=null;st.addEventListener('touchstart',function(e){x0=e.touches[0].clientX;},{passive:true});st.addEventListener('touchend',function(e){if(x0===null)return;var dx=e.changedTouches[0].clientX-x0;if(Math.abs(dx)>60)go(i+(dx<0?1:-1));x0=null;});
[].forEach.call(st.querySelectorAll('.lt-choice button'),function(b){b.addEventListener('click',function(){[].forEach.call(b.parentNode.children,function(x){x.setAttribute('aria-pressed',x===b?'true':'false');});var r=document.getElementById('ltRev1');r.textContent=b.dataset.c==='a'?'Everyone picks A. Yet business owners unknowingly run Budget B over and over, because the leaks are hard to see from the inside. Let us show you where they hide.':'Honest answer. Nobody wants B, and most owners running it do not know they are. Let us show you where the leaks usually are.';r.classList.add('show');});});
var sp=document.getElementById('ltSpend'),wk=document.getElementById('ltWork');function leak(){document.getElementById('ltSpendO').textContent=(+sp.value).toLocaleString('en-US');document.getElementById('ltWorkO').textContent=wk.value;document.getElementById('ltLeak').textContent='$'+Math.round(sp.value*(1-wk.value/100)*12).toLocaleString('en-US');}sp.addEventListener('input',leak);wk.addEventListener('input',leak);leak();
[].forEach.call(st.querySelectorAll('.lt-react button'),function(b){b.addEventListener('click',function(){var o=b.parentNode.nextElementSibling;o.textContent=b.dataset.r;o.classList.add('show');});});
var chatT=null;function chat(){var m=st.querySelectorAll('.lt-msg');[].forEach.call(m,function(x){x.classList.remove('in');});[].forEach.call(m,function(x,k){setTimeout(function(){x.classList.add('in');},500+k*1100);});}
var obs=new MutationObserver(function(){if(S[5].classList.contains('on'))chat();});obs.observe(S[5],{attributes:true,attributeFilter:['class']});
function quote(){var p=st.querySelectorAll('.lt-qt .pill[data-p]'),pr=document.getElementById('ltPrice');[].forEach.call(p,function(x){x.classList.remove('on');});pr.firstChild.textContent='$ \u2014';setTimeout(function(){p[0].classList.add('on');},700);setTimeout(function(){p[1].classList.add('on');},1400);setTimeout(function(){pr.firstChild.textContent='$9,800 \u2013 $14,500';},2100);}
var fit=st.querySelectorAll('.lt-fit button');[].forEach.call(fit,function(b){b.addEventListener('click',function(){b.setAttribute('aria-pressed',b.getAttribute('aria-pressed')==='true'?'false':'true');var n=st.querySelectorAll('.lt-fit button[aria-pressed="true"]').length;document.getElementById('ltMatch').classList.toggle('show',n>=3);});});
document.getElementById('ltYes').addEventListener('click',function(){document.getElementById('ltYay').classList.add('show');});
function fitStage(){st.style.minHeight='';var m=0;S.forEach(function(s){m=Math.max(m,s.scrollHeight);});st.style.minHeight=m+'px';}fitStage();st.addEventListener('click',function(){setTimeout(fitStage,60);});window.addEventListener('resize',fitStage);window.addEventListener('load',fitStage);if(document.fonts&&document.fonts.ready)document.fonts.ready.then(fitStage);
go(0);})();
